# fly.toml app configuration file generated for dactylo-staging on 2023-12-28T22:50:01-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dactylo-staging"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
